// <auto-generated />
using System;
using System.Collections.Generic;
using CampusSpace.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace CampusSpace.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampusSpace.Api.Models.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<string>>("Nodes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("OfficerSummary")
                        .HasColumnType("text");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PolicySnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProposalJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "RevisionNo")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex(new[] { "RequestId" }, "IX_AgentRuns_RequestId_Live")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Queued', 'Running', 'AwaitingApproval', 'Resuming')");

                    b.ToTable("AgentRuns", t =>
                        {
                            t.HasCheckConstraint("CK_AgentRuns_CompletedAt_After_StartedAt", "\"StartedAt\" IS NULL OR \"CompletedAt\" IS NULL OR \"CompletedAt\" >= \"StartedAt\"");

                            t.HasCheckConstraint("CK_AgentRuns_DurationMs", "\"DurationMs\" IS NULL OR \"DurationMs\" >= 0");

                            t.HasCheckConstraint("CK_AgentRuns_FailureReason", "\"Status\" <> 'Failed' OR \"FailureReason\" IS NOT NULL");

                            t.HasCheckConstraint("CK_AgentRuns_RevisionNo", "\"RevisionNo\" > 0");

                            t.HasCheckConstraint("CK_AgentRuns_Status", "\"Status\" IN ('Queued', 'Running', 'AwaitingApproval', 'Resuming', 'Completed', 'Rejected', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Retries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("AgentSteps", t =>
                        {
                            t.HasCheckConstraint("CK_AgentSteps_AgentName_NotBlank", "btrim(\"AgentName\") <> ''");

                            t.HasCheckConstraint("CK_AgentSteps_DurationMs", "\"DurationMs\" >= 0");

                            t.HasCheckConstraint("CK_AgentSteps_Retries", "\"Retries\" >= 0");

                            t.HasCheckConstraint("CK_AgentSteps_Sequence", "\"Sequence\" >= 1");

                            t.HasCheckConstraint("CK_AgentSteps_Status", "\"Status\" IN ('Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentToolCall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArgsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("jsonb");

                    b.Property<long>("StepId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("AgentToolCalls", t =>
                        {
                            t.HasCheckConstraint("CK_AgentToolCalls_DurationMs", "\"DurationMs\" >= 0");

                            t.HasCheckConstraint("CK_AgentToolCalls_Error", "\"Succeeded\" OR \"Error\" IS NOT NULL");

                            t.HasCheckConstraint("CK_AgentToolCalls_ToolName_NotBlank", "btrim(\"ToolName\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentValidationResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Attempt", "RuleCode")
                        .IsUnique();

                    b.ToTable("ValidationResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_ValidationResults_Attempt", "\"Attempt\" > 0");

                            t.HasCheckConstraint("CK_ValidationResults_RuleCode", "\"RuleCode\" ~ '^V(0[1-9]|1[0-2])$'");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.ApprovalDecision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("OfficerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("RequestId");

                    b.ToTable("ApprovalDecisions", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalDecisions_Comment", "\"Decision\" = 'Approve' OR (\"Comment\" IS NOT NULL AND btrim(\"Comment\") <> '')");

                            t.HasCheckConstraint("CK_ApprovalDecisions_Decision", "\"Decision\" IN ('Approve', 'Reject', 'Revise')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<NpgsqlRange<DateTime>>("TimeRange")
                        .HasColumnType("tstzrange");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Status", "\"Status\" IN ('Confirmed', 'CheckedIn', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("CK_Bookings_TimeRange", "NOT isempty(\"TimeRange\") AND NOT lower_inf(\"TimeRange\") AND NOT upper_inf(\"TimeRange\") AND lower_inc(\"TimeRange\") AND NOT upper_inc(\"TimeRange\")");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.BookingRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attendees")
                        .HasColumnType("integer");

                    b.Property<decimal>("BudgetLkr")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CancelledByOfficer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long?>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLateCancellation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RequestedEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint");

                    b.Property<List<string>>("RequiredFeatures")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("RequesterId", "Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("BookingRequests", t =>
                        {
                            t.HasCheckConstraint("CK_BookingRequests_Attendees", "\"Attendees\" BETWEEN 1 AND 2000");

                            t.HasCheckConstraint("CK_BookingRequests_BudgetLkr", "\"BudgetLkr\" >= 0");

                            t.HasCheckConstraint("CK_BookingRequests_Cancellation_NotLateAndOfficer", "NOT (\"IsLateCancellation\" AND \"CancelledByOfficer\")");

                            t.HasCheckConstraint("CK_BookingRequests_CancelledAt_Status", "\"CancelledAt\" IS NULL OR \"Status\" = 'Cancelled'");

                            t.HasCheckConstraint("CK_BookingRequests_Purpose_NotBlank", "btrim(\"Purpose\") <> ''");

                            t.HasCheckConstraint("CK_BookingRequests_RequestedEnd_After_Start", "\"RequestedEnd\" > \"RequestedStart\"");

                            t.HasCheckConstraint("CK_BookingRequests_Status", "\"Status\" IN ('Submitted', 'AgentProcessing', 'PendingApproval', 'Approved', 'Completed', 'AgentFailed', 'RevisionRequested', 'Rejected', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Building", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Buildings", t =>
                        {
                            t.HasCheckConstraint("CK_Buildings_Code_Format", "\"Code\" ~ '^[A-Z0-9][A-Z0-9-]*$'");

                            t.HasCheckConstraint("CK_Buildings_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Club", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clubs", t =>
                        {
                            t.HasCheckConstraint("CK_Clubs_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.ClubMember", b =>
                {
                    b.Property<long>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClubId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClubId" }, "IX_ClubMembers_OneRepresentative")
                        .IsUnique()
                        .HasFilter("\"IsRepresentative\"");

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("TypeId", "Status");

                    b.ToTable("EquipmentItems", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentItems_AssetTag_NotBlank", "btrim(\"AssetTag\") <> ''");

                            t.HasCheckConstraint("CK_EquipmentItems_Condition", "\"Condition\" IN ('Good', 'MinorWear', 'Damaged')");

                            t.HasCheckConstraint("CK_EquipmentItems_Status", "\"Status\" IN ('Available', 'OnLoan', 'UnderRepair', 'Retired')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentLoan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CheckedInById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CheckedOutById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DamagePhotoPath")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLateReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReturnCondition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CheckedInById");

                    b.HasIndex("CheckedOutById");

                    b.HasIndex("ItemId");

                    b.HasIndex(new[] { "DueAt" }, "IX_EquipmentLoans_DueAt_Open")
                        .HasFilter("\"CheckedInAt\" IS NULL");

                    b.HasIndex(new[] { "ItemId" }, "IX_EquipmentLoans_ItemId_Open")
                        .IsUnique()
                        .HasFilter("\"CheckedInAt\" IS NULL");

                    b.ToTable("EquipmentLoans", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentLoans_CheckIn", "(\"CheckedInAt\" IS NULL AND \"CheckedInById\" IS NULL AND \"ReturnCondition\" IS NULL AND \"DamageNote\" IS NULL AND \"DamagePhotoPath\" IS NULL AND NOT \"IsLateReturn\") OR (\"CheckedInAt\" IS NOT NULL AND \"CheckedInById\" IS NOT NULL AND \"ReturnCondition\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_EquipmentLoans_CheckedInAt", "\"CheckedInAt\" >= \"CheckedOutAt\"");

                            t.HasCheckConstraint("CK_EquipmentLoans_DamagePhotoPath", "\"DamagePhotoPath\" ~ '^[0-9a-f]{32}\\.(jpg|png)$'");

                            t.HasCheckConstraint("CK_EquipmentLoans_Damaged", "\"ReturnCondition\" IS DISTINCT FROM 'Damaged' OR (\"DamageNote\" IS NOT NULL AND \"DamagePhotoPath\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_EquipmentLoans_DueAt", "\"DueAt\" > \"CheckedOutAt\"");

                            t.HasCheckConstraint("CK_EquipmentLoans_ReturnCondition", "\"ReturnCondition\" IN ('Good', 'MinorWear', 'Damaged')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentReservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<NpgsqlRange<DateTime>>("TimeRange")
                        .HasColumnType("tstzrange");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "TypeId")
                        .IsUnique();

                    b.HasIndex(new[] { "TypeId", "TimeRange" }, "IX_EquipmentReservations_TypeId_TimeRange");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "TypeId", "TimeRange" }, "IX_EquipmentReservations_TypeId_TimeRange"), "gist");

                    b.ToTable("EquipmentReservations", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentReservations_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_EquipmentReservations_TimeRange", "NOT isempty(\"TimeRange\") AND NOT lower_inf(\"TimeRange\") AND NOT upper_inf(\"TimeRange\") AND lower_inc(\"TimeRange\") AND NOT upper_inc(\"TimeRange\")");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentSubstitute", b =>
                {
                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubstituteTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TypeId", "SubstituteTypeId");

                    b.HasIndex("SubstituteTypeId");

                    b.ToTable("EquipmentSubstitutes", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentSubstitutes_NotSelf", "\"TypeId\" <> \"SubstituteTypeId\"");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CoveredByFeatureCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeePerBooking")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CoveredByFeatureCode");

                    b.ToTable("EquipmentTypes", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentTypes_Category", "\"Category\" IN ('Audio', 'Visual', 'Computing', 'Presentation', 'Accessory')");

                            t.HasCheckConstraint("CK_EquipmentTypes_Code_Format", "\"Code\" ~ '^[A-Z0-9]+(-[A-Z0-9]+)*$' AND char_length(\"Code\") >= 2");

                            t.HasCheckConstraint("CK_EquipmentTypes_FeePerBooking", "\"FeePerBooking\" >= 0");

                            t.HasCheckConstraint("CK_EquipmentTypes_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Features", t =>
                        {
                            t.HasCheckConstraint("CK_Features_Code_Format", "\"Code\" ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_Features_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.PolicySetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PolicySettings", t =>
                        {
                            t.HasCheckConstraint("CK_PolicySettings_Key", "\"Key\" IN ('opening_hours', 'min_lead_time_hours', 'max_advance_days_student', 'max_advance_days_lecturer', 'max_duration_hours', 'max_capacity_ratio', 'slot_granularity_minutes', 'free_cancellation_hours', 'max_open_requests', 'checkout_window_minutes')");

                            t.HasCheckConstraint("CK_PolicySettings_ValueType", "\"ValueType\" IN ('int', 'decimal', 'bool', 'json')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.PricingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsExempt")
                        .HasColumnType("boolean");

                    b.Property<string>("RequesterRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoomType", "RequesterRole", "ValidFrom" }, "IX_PricingRules_RoomType_RequesterRole_ValidFrom")
                        .IsUnique();

                    b.ToTable("PricingRules", t =>
                        {
                            t.HasCheckConstraint("CK_PricingRules_Exempt_ZeroRate", "NOT \"IsExempt\" OR \"HourlyRate\" = 0");

                            t.HasCheckConstraint("CK_PricingRules_HourlyRate", "\"HourlyRate\" >= 0");

                            t.HasCheckConstraint("CK_PricingRules_RequesterRole", "\"RequesterRole\" IN ('Student', 'Lecturer')");

                            t.HasCheckConstraint("CK_PricingRules_RoomType", "\"RoomType\" IN ('LectureHall', 'ComputerLab', 'SeminarRoom', 'Auditorium')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Quotation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsExempt")
                        .HasColumnType("boolean");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("RequestId");

                    b.HasIndex(new[] { "RequestId" }, "IX_Quotations_RequestId_Live")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Draft', 'Issued')");

                    b.ToTable("Quotations", t =>
                        {
                            t.HasCheckConstraint("CK_Quotations_Discount", "\"Discount\" >= 0");

                            t.HasCheckConstraint("CK_Quotations_Discount_LE_Subtotal", "\"Discount\" <= \"Subtotal\"");

                            t.HasCheckConstraint("CK_Quotations_Exempt", "NOT \"IsExempt\" OR (\"Discount\" = \"Subtotal\" AND \"DiscountReason\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Quotations_Status", "\"Status\" IN ('Draft', 'Issued', 'Void')");

                            t.HasCheckConstraint("CK_Quotations_Subtotal", "\"Subtotal\" >= 0");

                            t.HasCheckConstraint("CK_Quotations_Total", "\"Total\" >= 0");

                            t.HasCheckConstraint("CK_Quotations_Total_Equals_Subtotal_Minus_Discount", "\"Total\" = \"Subtotal\" - \"Discount\"");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.QuotationLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("EquipmentTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric(10,2)");

                    b.Property<long>("QuotationId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationLines", t =>
                        {
                            t.HasCheckConstraint("CK_QuotationLines_Kind", "\"Kind\" IN ('Room', 'Equipment')");

                            t.HasCheckConstraint("CK_QuotationLines_Kind_Type", "(\"Kind\" = 'Room') = (\"EquipmentTypeId\" IS NULL)");

                            t.HasCheckConstraint("CK_QuotationLines_LineTotal", "\"LineTotal\" = round(\"Qty\" * \"UnitPrice\", 2)");

                            t.HasCheckConstraint("CK_QuotationLines_Qty", "\"Qty\" > 0");

                            t.HasCheckConstraint("CK_QuotationLines_UnitPrice", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ChangedById")
                        .HasColumnType("bigint");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("RequestId", "ChangedAt");

                    b.ToTable("RequestStatusHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_RequestStatusHistory_FromStatus", "\"FromStatus\" IS NULL OR \"FromStatus\" IN ('Submitted', 'AgentProcessing', 'PendingApproval', 'Approved', 'Completed', 'AgentFailed', 'RevisionRequested', 'Rejected', 'Cancelled')");

                            t.HasCheckConstraint("CK_RequestStatusHistory_ToStatus", "\"ToStatus\" IN ('Submitted', 'AgentProcessing', 'PendingApproval', 'Approved', 'Completed', 'AgentFailed', 'RevisionRequested', 'Rejected', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestedEquipmentLine", b =>
                {
                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("RequestId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("RequestedEquipmentLines", t =>
                        {
                            t.HasCheckConstraint("CK_RequestedEquipmentLines_Quantity", "\"Quantity\" BETWEEN 1 AND 50");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BuildingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Capacity");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rooms", t =>
                        {
                            t.HasCheckConstraint("CK_Rooms_Capacity", "\"Capacity\" > 0");

                            t.HasCheckConstraint("CK_Rooms_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_Rooms_Name_NotBlank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_Rooms_Type", "\"Type\" IN ('LectureHall', 'ComputerLab', 'SeminarRoom', 'Auditorium')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomBlackout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<NpgsqlRange<DateTime>>("TimeRange")
                        .HasColumnType("tstzrange");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex(new[] { "RoomId", "TimeRange" }, "IX_RoomBlackouts_RoomId_TimeRange");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "RoomId", "TimeRange" }, "IX_RoomBlackouts_RoomId_TimeRange"), "gist");

                    b.ToTable("RoomBlackouts", t =>
                        {
                            t.HasCheckConstraint("CK_RoomBlackouts_Reason_NotBlank", "btrim(\"Reason\") <> ''");

                            t.HasCheckConstraint("CK_RoomBlackouts_TimeRange", "NOT isempty(\"TimeRange\") AND NOT lower_inf(\"TimeRange\") AND NOT upper_inf(\"TimeRange\") AND lower_inc(\"TimeRange\") AND NOT upper_inc(\"TimeRange\")");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomFeature", b =>
                {
                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<long>("FeatureId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoomId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RoomFeatures");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Student', 'Lecturer', 'LabTechnician', 'FacilitiesOfficer', 'Admin')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentRun", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentStep", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.AgentRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentToolCall", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.AgentStep", "Step")
                        .WithMany("ToolCalls")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentValidationResult", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.AgentRun", "Run")
                        .WithMany("ValidationResults")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.ApprovalDecision", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.AgentRun", "AgentRun")
                        .WithMany()
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.User", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentRun");

                    b.Navigation("Officer");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AuditLog", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Booking", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithOne()
                        .HasForeignKey("CampusSpace.Api.Models.Booking", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.BookingRequest", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusSpace.Api.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.ClubMember", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentItem", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "Type")
                        .WithMany("Items")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentLoan", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.User", "CheckedInBy")
                        .WithMany()
                        .HasForeignKey("CheckedInById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusSpace.Api.Models.User", "CheckedOutBy")
                        .WithMany()
                        .HasForeignKey("CheckedOutById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.EquipmentItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("CheckedInBy");

                    b.Navigation("CheckedOutBy");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentReservation", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentSubstitute", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "SubstituteType")
                        .WithMany()
                        .HasForeignKey("SubstituteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "Type")
                        .WithMany("Substitutes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubstituteType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentType", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Feature", "CoveredByFeature")
                        .WithMany()
                        .HasForeignKey("CoveredByFeatureCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoveredByFeature");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.PolicySetting", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Quotation", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.AgentRun", "AgentRun")
                        .WithMany()
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentRun");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.QuotationLine", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusSpace.Api.Models.Quotation", "Quotation")
                        .WithMany("Lines")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestStatusHistory", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestedEquipmentLine", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithMany("EquipmentLines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Room", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomBlackout", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.Room", "Room")
                        .WithMany("Blackouts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomFeature", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.Room", "Room")
                        .WithMany("RoomFeatures")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentRun", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("ValidationResults");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AgentStep", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.BookingRequest", b =>
                {
                    b.Navigation("EquipmentLines");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Club", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentType", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Quotation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Room", b =>
                {
                    b.Navigation("Blackouts");

                    b.Navigation("RoomFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
